import Head from "next/head";
import Header from "@/components/HomeComponents/Header";
import { getKits } from "@/api/kits";
import FeaturedSectionKits from "@/components/FeaturedSectionKits";

const Home = ({ kitsFeatured, kitsBestsellers, kitsDesc }) => {
  return (
    <>
      <Head>
        <title>Armattan</title>
        <meta name="description" content="Generated by armattan" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className="mt-5">
        <FeaturedSectionKits
          kitsBestsellers={kitsBestsellers}
          kitsFeatured={kitsFeatured}
          kitsDesc={kitsDesc}
        />
      </div>
      {/* <div>
        <FeaturedSectionProducts />
      </div> */}
    </>
  );
};

export const getServerSideProps = async (ctx) => {
  let error;
  try {
    const kitsFeatured = await getKits({
      size: 5,
      page: 1,
      sort: "featured",
    }).catch((err) => {
      error = err?.response?.data?.detail;
    });
    const kitsBestsellers = await getKits({
      size: 5,
      page: 1,
      sort: "bestsellers",
    }).catch((err) => {
      error = err?.response?.data?.detail;
    });
    const kitsDesc = await getKits({
      size: 5,
      page: 1,
      sort: "desc",
    }).catch((err) => {
      error = err?.response?.data?.detail;
    });

    return {
      props: {
        kitsFeatured: kitsFeatured.data,
        kitsBestsellers: kitsBestsellers.data,
        kitsDesc: kitsDesc.data,
      },
    };
  } catch (err) {
    return {
      props: {
        error,
      },
    };
  }
};

export default Home;
