import Head from "next/head";
import Header from "@/components/HomeComponents/Header";
// import TopCategories from "@/components/HomeComponents/TopCategories";
import { getCategories } from "@/api/categories";
import { getProducts, getProductsCategories } from "@/api/products";
import BestSellersSection from "@/components/HomeComponents/BestSellersSection";
import FeaturedSection from "@/components/HomeComponents/FeaturedSection";
import TopNavbar from "@/components/HomeComponents/TopNavbar";
import Menubar from "@/components/Menubar";
import dynamic from "next/dynamic";
import { getKitsCategories } from "@/api/kits";
import { getHardwareCategories } from "@/api/hardwares";

const TopCategories = dynamic(
  () => import("@/components/HomeComponents/TopCategories"),
  { ssr: false }
);

const Home = ({ categories, products }) => {
  return (
    <>
      <Head>
        <title>Armattan</title>
        <meta name="description" content="Generated by armattan" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <TopCategories categories={categories} />
      <BestSellersSection products={products} />
      <FeaturedSection products={products} />
    </>
  );
};

export const getServerSideProps = async (ctx) => {
  const categoriesRes = await getCategories({ size: 5 });
  const productsRes = await getProducts({ size: 5, page: 1, sort: "asc" });

  return {
    props: {
      categories: categoriesRes.data,
      products: productsRes.data,
    },
  };
};

export default Home;
